/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("../Modelos/bad.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_1.geometry}
        material={nodes.Sphere_1.material}
        position={[1.35, -1.71, 0.26]}
        scale={[-0.3, 0.3, 0.3]}
      />
    </group>
  );
}

useGLTF.preload("../Modelos/bad.glb");
