/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: daedaljs (https://sketchfab.com/daedalJS)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stage-curtains-6b18d65628334387a71115f939de70c7
title: Stage Curtains
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("../Modelos/cortina.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 6.33]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Stage_Curtains_0.geometry}
            material={materials.beams}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../Modelos/cortina.glb");
